### ISSUE TITLE
Require some help for restart

### ISSUE THREAD

**Issue by PeterHagen** [anthturner/UniFiSharp#14]
Thanks for the helpful project. I have some issues with attempting to restart a device with the api. Its seems that my AP's have to be restart occasionally, so I thought that was a good moment to try and use this project. I created a test project, retrieved the devices, found one specific AP, and called ```api.NetworkDeviceRestart(device.mac)```. But, nothing seems to happen. Do I have to confirm the action? Its hard to debug the api request due to no message is being returned.

Here my example code:

```
using (var api = new UniFiSharp.UniFiApi(
    new Uri("https://..."), "...", "...", "default", false, false))
{
    await api.Authenticate();

    IEnumerable<UniFiSharp.Json.JsonNetworkDevice> uniFiDevices = await api.NetworkDeviceList();

    var count = uniFiDevices.Count();
    Assert.True(count > 0);

    var wifi = uniFiDevices
        .Where(u => string.Equals(u.type, "uap", StringComparison.InvariantCultureIgnoreCase))
        .ToList();
    
    foreach (var device in wifi)
    {
        if (device.mac == "78:8a:20:48:cc:dd")
        {
            await api.NetworkDeviceRestart(device.mac);
        }
    }
}
```

**Comment by anthturner** [comment]
@PeterHagen Is this still an issue after the PR?

**Comment by anthturner** [comment]
This appears to have been fixed by the user. Closing. Please let me know if it's still an issue.

**Comment by PeterHagen** [comment]
Sorry, I didn't see a notification about your reply. I'll try it in a few days

**Comment by PeterHagen** [comment]
Yes! It works! Thanks for the merge
