### ISSUE TITLE
Create voucher error 

### ISSUE THREAD

**Issue by honganhpmth90** [anthturner/UniFiSharp#3]
i'm using this code bellow for create new voucher.

but receive error. where is wrong ?

what sample value of : string quota, and string expire ?

[AllowAnonymous]
        [HttpGet, Route("createvoucher/{sitename}/{username}/{password}")]
        [ResponseHttpStatusCode(HttpStatusCode.NoContent, HttpStatusCode.NotFound)]
        [ProducesDefaultResponseType(typeof(IEnumerable<JsonHotspotVoucher>))]
        public async Task<IEnumerable<JsonHotspotVoucher>> createvoucher(string sitename, string username, string password)
        {
            IEnumerable<JsonHotspotVoucher> hotspotVouchers;
            using (var api = new UniFiSharp.UniFiApi(new Uri("https://118.69.70.156:8443"), username, password, sitename))
            {
                await api.Authenticate();
                JsonHotspotVoucher jsonHotspotVoucher = await api.HotspotVoucherAdd(8, 4096, 1024, "6hours", "500mb", "guest voucher");
                hotspotVouchers = await api.HotspotVoucherList();
            }
            return hotspotVouchers;
        }

**Comment by TobiKr** [comment]
The parameter quota is not the traffic quota, but the number of times you are allowed to reuse a voucher code. You will find a documentation here: 
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L2051

**Comment by anthturner** [comment]
If this is still an issue, please reply. Otherwise I will close this in the coming weeks.

**Comment by captainqwerty** [comment]
Recommend closing this ticket?

**Comment by anthturner** [comment]
Agreed. Closing due to lack of response.
