### ISSUE TITLE
Selfsigned certs not supported - v1.2 was never published!

### ISSUE THREAD

**Issue by Rammesses** [anthturner/UniFiSharp#7]
The Self-signed certificate support introduced in commit [dd113c1 ](https://github.com/anthturner/UniFiSharp/commit/dd113c103d5ba64eebdbcf028c40edb00b88531f)on 14 May 2018 has never been released to NuGet.

Can v1.2 be released please? :)

**Comment by anthturner** [comment]
I'll do you one better; I just published v1.3.0 with 2FA capability.
