### ISSUE TITLE
[Question] - does it support MFA

### ISSUE THREAD

**Issue by robgarrett** [anthturner/UniFiSharp#8]
I have my Unifi controller behind two factor auth. Will this lib support it?

Thanks,

R.

**Comment by anthturner** [comment]
Unfortunately it does not. I am accepting PRs for this though, if you (or anyone else who passes by this) would like to contribute.

**Comment by anthturner** [comment]
I did a little investigating and this shouldn't be too bad. Looks like on login, if the HTTP code comes back 499, we need to POST to "login/2fa" the JSON document "{'token':'<<token>>'}"

If anyone wants to implement/test that, be my guest. I'll try to get to it soon, but "soon" may still mean weeks.

**Comment by anthturner** [comment]
This was _far_ less effort than expected. I also made a change to account for the new version of the software.

I need community feedback on the branch: https://github.com/anthturner/UniFiSharp/tree/twoFactor

One of the changes is making all requests go through "/proxy/network", which I don't know if that applies globally.

**Comment by anthturner** [comment]
Added a "useModernApi" boolean to constructors to handle this in 1.3.0 release.
